### ISSUE TITLE
[Feat. Req.] Upload to IMGUR

### ISSUE THREAD

**Issue by momoe** [martyr-deepin/deepin-screenshot#35] opened 2018-08-21 21:05 UTC
http://imgur.com

Please provide an upload option to this site.

**Comment by weeman1337** [comment] 2019-07-08 09:47
This is a duplicate of #4

**Comment by BLumia** [comment] 2019-07-09 05:44
Duplicated with #4 , thanks for reporting :)

**Closed as completed by BLumia** 2019-07-09 05:44 UTC
